# Generated by Django 5.1.6 on 2025-04-06 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_roadmap'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='updated_at',
        ),
    ]
