# Generated by Django 4.2.7 on 2025-08-05 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="RoadmapRequest",
        ),
    ]
